import streamlit as st
import torch
import torch.nn as nn
import sys
from pathlib import Path
from PIL import Image
import plotly.express as px
import numpy as np
from torchvision import transforms

# 1. Setup paths so Streamlit can see your root modules cleanly
BASE_DIR = Path(__file__).resolve().parent.parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))

# Import the actual functional builder from your models/model.py file
from models.model import build_model as customized_model_builder

st.set_page_config(page_title="AI Diagnosis Engine", page_icon="🩺", layout="wide")

st.title(" AI-Powered Chest X-ray Diagnosis")
st.markdown("Upload a patient's chest X-ray to perform real-time diagnostic evaluation using your global Federated Learning model.")
st.markdown("---")

# The 6 core target diseases handled by LifeSync
CLASSES = ['No Finding', 'Atelectasis', 'Cardiomegaly', 'Effusion', 'Pneumothorax', 'Pneumonia']

@st.cache_resource
def load_actual_weights():
    # Target the exact checkpoint shown in your checkpoints folder
    checkpoint_path = BASE_DIR / "checkpoints" / "best_global_model.pth"
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    # Run YOUR builder function with 6 classes to match the dataset targets
    net = customized_model_builder(num_classes=len(CLASSES))
    
    # Load your trained weights onto the allocated device
    net.load_state_dict(torch.load(checkpoint_path, map_location=device))
    net.eval()
    
    return net, device

# Initialize the inference engine safely
try:
    net, device = load_actual_weights()
    st.sidebar.success("✅ best_global_model.pth integrated successfully!")
except Exception as e:
    st.sidebar.error(f"❌ Weight linkage failed. Error: {e}")
    st.stop()  # Halt execution if the model fails to load properly

# 2. Define Image Preprocessing Pipeline (Standard ResNet ImageNet normalizations)
preprocess = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# 3. UI File Dropzone Area
uploaded_file = st.file_uploader("Choose a Chest X-ray Image (PNG, JPG, JPEG)...", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Open the uploaded user image frame
    image = Image.open(uploaded_file).convert('RGB')
    
    # Create matching 2-column layout for Preview vs Diagnostics
    col1, col2 = st.columns([1, 1.2], gap="large")
    
    with col1:
        st.markdown("### 📷 Uploaded X-ray Preview")
        st.image(image, use_container_width=True, caption="Active Patient Scan Frame")
        
    with col2:
        st.markdown("### 📊 Live Diagnostic Analysis")
        
        with st.spinner("Processing image matrices through ResNet18 layers..."):
            # Transform image to match network expected tensor shape [1, 3, 224, 224]
            input_tensor = preprocess(image).unsqueeze(0).to(device)
            
            # Execute actual forward pass (No gradients computed during inference)
            with torch.no_grad():
                outputs = net(input_tensor)
                # Convert raw logit vectors to clean probability distributions
                probabilities = torch.nn.functional.softmax(outputs, dim=1)[0].cpu().numpy()
            
            # Extract highest probability index metrics
            best_idx = np.argmax(probabilities)
            predicted_class = CLASSES[best_idx]
            confidence = probabilities[best_idx]
            
            # Map all true classes to their calculated scores for the graph
            prob_matrix = {CLASSES[i]: float(probabilities[i]) for i in range(len(CLASSES))}
        
        # Display the REAL dynamic metrics generated by your model execution pass
        metric_col1, metric_col2 = st.columns(2)
        metric_col1.metric("Predicted Condition Classification", predicted_class)
        metric_col2.metric("Confidence Level Metric", f"{confidence * 100:.1f}%")
        
        st.markdown("#### Probability Matrix Distribution")
        
        # Render a clean, interactive horizontal bar chart bound to your model arrays
        fig = px.bar(
            x=list(prob_matrix.values()),
            y=list(prob_matrix.keys()),
            orientation='h',
            labels={'x': 'Probability Score Value', 'y': 'Pathology Category'},
            color=list(prob_matrix.values()),
            color_continuous_scale="Blues"
        )
        fig.update_layout(showlegend=False, height=300, margin=dict(l=0, r=0, t=10, b=10))
        st.plotly_chart(fig, use_container_width=True)
else:
    st.info("Awaiting X-ray scan drop configuration to begin inference compilation.")